---
- name: Ensure software-properties is installed
  apt:
    name: software-properties-common
    state: present
    update_cache: yes
    cache_valid_time: 3600

- name: Add repository
  apt_repository:
    repo: 'ppa:certbot/certbot'
    state: present
    update_cache: yes

- name: Install Certbot.
  apt:
    name: '{{ certbot_package }}'
    state: present
    update_cache: yes
    cache_valid_time: 3600
